### ISSUE TITLE
swapChain.getCurrentTexture()引发浏览器崩溃

### ISSUE THREAD

**Issue by shawn0326** [hjlld/LearningWebGPU#1]
Chrome ver：版本 82.0.4051.0（正式版本）canary （64 位）
试了网上其它WebGPU的例子也会崩溃，有可能是浏览器的bug？

**Comment by hjlld** [comment]
用 canary 应该没问题，如果有问题就是浏览器 bug

**Comment by shawn0326** [comment]
> 用 canary 应该没问题，如果有问题就是浏览器 bug

我之后又更新了浏览器版本，没有问题了。看来是该版本canary浏览器的BUG。
