### ISSUE TITLE
关于 DEMO 在 Canary 87 版本报错: createBufferMapped is not function 的问题

### ISSUE THREAD

**Issue by mango-FullStack** [hjlld/LearningWebGPU#11]
在最新的 webgpu 标准中好像由于 device.createBufferMapped 存在不会自动清除内存的问题 被干掉了,  需要使用 device.createBuffer 方法取代掉
调用方式如下
`const GPUBuffer = await this.device.createBuffer({ size, usage, mappedAtCreation: true })`
`new TypedArray.constructor(GPUBuffer.getMappedRange()).set(TypedArray, 0)`
`GPUBuffer.unmap()`

**Comment by hjlld** [comment]
已经修复，感谢！
