### ISSUE TITLE
lesson 5 code app.ts

### ISSUE THREAD

**Issue by notthistrain** [hjlld/LearningWebGPU#46]
调试代码时浏览器控制台给出了警告：The size of the resolve target must be the same as the color attachment，并且没有绘制图形。
我将app.ts中第75、77、97、99行中的  ‘ * window.devicePixelRatio’  删掉后，能正常绘制图形。
操作系统是macos。

**Comment by hjlld** [comment]
https://github.com/hjlld/LearningWebGPU/blob/b305b78f24475c3c5a350d1350cc76e6addf82fa/Lesson5_Texture/Code/src/app.ts#L33-L35
```
       this.canvas.width = width * window.devicePixelRatio;
       this.canvas.height = height * window.devicePixelRatio;
```

这里 `canvas` 的 `width` 和 `height` 应该也乘以 `window.devicePixelRatio`，我手头没有高分屏，回头测试一下

**Comment by hjlld** [comment]
should be fixed by https://github.com/hjlld/LearningWebGPU/commit/1d9d5f3ff13354867e2b73af352bfa93641fcccb
