### ISSUE TITLE
针对getContext方法，教程代码是否需要改成webgpu上下文了

### ISSUE THREAD

**Issue by liuguanyu** [hjlld/LearningWebGPU#59]
感谢您写了这么多通俗易懂的教程。受益匪浅。

提一个小瑕疵。我看您的Code里`canvas.getContext( 'webgpu' )`里面都已经用webgpu上下文了。您看教程里的gpupresent是否需要同步改为webgpu。

谢谢。

**Comment by hjlld** [comment]
不好意思，最近比较忙，我抽空会更新一下教程。
这段时间教程更新的比较慢，主要是之前更新的比较频繁，而WebGPU标准更新的也比较频繁，这样就需要反复改动，很多API被直接取消，导致教程的内容作废。处理起来挺麻烦的。

**Comment by liuguanyu** [comment]
> 不好意思，最近比较忙，我抽空会更新一下教程。 这段时间教程更新的比较慢，主要是之前更新的比较频繁，而WebGPU标准更新的也比较频繁，这样就需要反复改动，很多API被直接取消，导致教程的内容作废。处理起来挺麻烦的。

辛苦，跟进新标准是个麻烦事，看您已经坚持好久了，希望不要弃坑，加油！
